name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Extract version from tag
        id: extract_version
        run: |
          # Extract the version from the release tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Delete version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -d "v${{ env.VERSION }}"
          git push origin --delete "v${{ env.VERSION }}"

      - name: Bump version in package.json
        run: |
          echo "Bumping version to ${{ env.VERSION }}"
          npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "Bump version to ${{ env.VERSION }}"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"

      - name: Push changes
        run: |
          git push
          git push origin "v${{ env.VERSION }}"

      - run: npm run build

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}